# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-10 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujian_aplikasi_1174035', '0002_auto_20191110_1805'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
