# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('namarek', models.CharField(max_length=128)),
                ('norek', models.CharField(max_length=128)),
                ('nama_bank', models.CharField(max_length=128)),
                ('ref', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
